name: intel-kodi-efi
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: submodule checkout
      run: |
        git submodule sync --recursive
        git submodule update --init --force --recursive --depth=1
    - name: install autopoint
      run: sudo apt update && sudo apt install autopoint
    - name: configure
      run: ./build.sh amd64_intel_kodi_defconfig
    - name: make
      run: ./build.sh all -j3
    - name: Archive linux.efi
      uses: actions/upload-artifact@v1
      with:
        name: code-coverage-report
        path: output/images/linux.efi
